services:
  jenkins:
    image: taehyunnkim/jenkins-docker-aws:latest
    # image: xinyiw12/jenkins-docker-azure:latest
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 127.0.0.1:50000:50000
    container_name: jenkins
    volumes:
      - /home/azureuser/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
    # - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
    - AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID
    - REGION=$REGION
  aws-credentials-generator-web:
    #image: taehyunnkim/odso-dashboard-app-cli:latest
    image: kevinkcy511/dashboard-frontend
    platform: linux/amd64
    # container_name: aws-credentials-generator-web
    container_name: azure-credentials-generator-web
    ports:
      - 127.0.0.1:7777:80
    environment:
      - REACT_APP_API_ENDPOINT=api.internal  # ✅ Ensures frontend calls backend correctly
  aws-credentials-generator-server:
      image: kevinkcy511/dashboard-backend
      platform: linux/amd64
      container_name: azure-credentials-generator-server
      ports:
        - 7778:7777
      environment:
        - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
        - REGION=$REGION
      networks:
        app_network:
          aliases:
            - api.internal
